### ISSUE TITLE
Cannot read properties of null

### ISSUE THREAD

**Issue by jvmonjo** [ItzNotABug/ghosler#39]
Hi. I have ghosler dockerized but I haven't managed to get it working. This is the error log it keeps showing when I publish a new post. 

'''
[ERROR] => Newsletter: TypeError: Cannot read properties of null (reading 'replace')
at Object.decode (/ghosler/node_modules/he/he.js:232:15)
at file:///ghosler/utils/newsletter.js:218:58
at Array.forEach (<anonymous>)
'''

**Comment by ItzNotABug** [comment]
Hey 👋,
a bug was recently fixed that had a similar signature. Whats the installed `ghosler` version on your server?

**Comment by jvmonjo** [comment]
Sorry. I couldn't find a similar issue the other day and today I have opened the issue maybe just too fast. I'm using the docker hub version 
hdsplus/ghosler:latest which I've just pulled and it seems it's using Ghosler 0.92

**Comment by jvmonjo** [comment]
I've just figured out I needed to remove the volume to rebuild the latest ghostlier version. I guess we need a better docker architecture so we don't have to remove ghosler data every time,e we need to update. 

Now I have 0.93 and a different error:

 [ERROR] => Newsletter: Error: C047036F917F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:354

**Comment by ItzNotABug** [comment]
> Sorry. I couldn't find a similar issue the other day and today I have opened the issue maybe just too fast. I'm using the docker hub version hdsplus/ghosler:latest which I've just pulled and it seems it's using Ghosler 0.92

Understood.
I do see that it was updated like 4 days ago, same day I released a fix for this.

You could either directly contact [@viriatusX](https://github.com/viriatusX) or see what link in your configuration is `null` at the moment. Does your Ghost site also contain an image logo? I mean that's something that could be `null`. Not sure any other URL would be null.

**Comment by ItzNotABug** [comment]
> I've just figured out I needed to remove the volume to rebuild the latest ghostlier version. I guess we need a better docker architecture so we don't have to remove ghosler data every time,e we need to update.
> 
> Now I have 0.93 and a different error:
> 
> [ERROR] => Newsletter: Error: C047036F917F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:354

Seems something with `ssl` maybe.

If the docker version is bumped to `0.93` in the meantime then that should be a stable build without any further issue while I investigate things for dockerizing `Ghosler`.

Thanks.

**Comment by ItzNotABug** [comment]
Hey @jvmonjo,
Ghosler now has official Docker support out of the box and has the latest source including the fix you are looking for.

Please refer the README on how to install Ghosler on Docker.

**Comment by jvmonjo** [comment]
Awesome implementation of the docker version. Now with persistent volumes for configuration, logs and analytics! Congrats!

Unfortunately I'm still getting ssl error, but it may be some configuration on my end, maybe with nginx proxy. I'll keep investigating.

```

Newsletter: Error: 683BFA09257F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354

```

**Comment by ItzNotABug** [comment]
Hey @jvmonjo,
a quick google search popped up this - https://stackoverflow.com/questions/50840101/curl-35-error1408f10bssl-routinesssl3-get-recordwrong-version-number

Possibly this could be helpful.

**Comment by jvmonjo** [comment]
Thanks. I've already fixed it!

In case anyone else struggles with this, I was just using the **wrong smtp port** on my configuration.
